version: "3.8"

services:
  cloud-sql-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: cloud-sql-proxy
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: django_container
    restart: always
    depends_on:
      - cloud-sql-proxy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app