version: "3.8"

services:
  #db:
  #  image: mysql:8
  #  container_name: mysql_container
  #  restart: always
  #  env_file:
  #    - .env
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_container
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

#volumes:
#  mysql_data:
