name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        working-directory: ./frontend

      - name: Run gradle tests
        run: ./gradlew test
        working-directory: ./frontend

      - name: Run gradle lint
        run: ./gradlew lint
        working-directory: ./frontend

      - name: Build gradle project
        run: ./gradlew build
        working-directory: ./frontend
